kind: Service
apiVersion: v1
metadata:
  name: wikijs-app
  labels:
    app: wikijs-app
    app.kubernetes.io/part-of: wikijs
    component: app 
spec:
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: wikijs-app
    deployment: wikijs-app
