apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs-app
  labels:
    app: wikijs-app
    app.kubernetes.io/part-of: wikijs
    component: app 
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: wikijs-app
      deployment: wikijs-app
  template:
    metadata:
      labels: 
        app: wikijs-app 
        deployment: wikijs-app
    spec:
      containers:
        - name: wikijs-app
          image: 'ghcr.io/bazzadev/wikijs-openshift:main'
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wikijs-db
                  key: POSTGRESQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wikijs-db
                  key: POSTGRESQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs-db
                  key: POSTGRESQL_PASSWORD
          envFrom:
            - configMapRef:
                name: wikijs-app
