apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  labels:
    app: wiki
    app.kubernetes.io/part-of: wikijs
    component: web
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: wiki
      deployment: wiki
  template:
    metadata:
      labels: 
        app: wiki 
        deployment: wiki
    spec:
      containers:
        - name: wiki
          image: 'ghcr.io/bazzadev/wikijs-openshift:main'
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: wikijs-db
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: wikijs
            - name: DB_PASS
              value: wikijsrocks
            - name: DB_NAME
              value: wiki
