apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs-db
  labels:
    app.kubernetes.io/part-of: wikijs
    component: database
    database: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs-db
  template:
    metadata:
      labels:
        app: wikijs-db
        deployment: wikijs-db
    spec:
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: wikijs-db
      containers:
      - name: wikijs-db
        image: 'registry.redhat.io/rhel8/postgresql-15'
        volumeMounts:
          - name: pv
            mountPath: /var/lib/pgsql/data
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
          - secretRef:
              name: wikijs-db
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile: 
            type: RuntimeDefault
