kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db
  app.kubernetes.io/part-of: wikijs
  component: database
  database: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
