kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db
  labels:
    app.kubernetes.io/part-of: wikijs
    component: database
    database: postgresqlspec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
