apiVersion: v1
kind: Secret
metadata:
  name: wikijs-db
  labels:
    app.kubernetes.io/part-of: wikijs
    component: database
    database: postgresql
stringData:
  POSTGRESQL_USER: wikijs
  POSTGRESQL_PASSWORD: wikijsrocks
  POSTGRESQL_DATABASE: wiki
