kind: Service
apiVersion: v1
metadata:
  name: wikijs-db
  labels:
    app.kubernetes.io/part-of: wikijs
    component: database
    database: postgresql
spec:
  selector:
    app: wikijs-db
    deployment: wikijs-db
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
